fix: Pdv 3 user registry proteggere le api di lettura con il namespace derivante da api key
pagopa/pdv-ms-user-registry pull request #15
Opened 2023-02-22 16:07 UTC by BenitoVisone

- fix namespace requirement and tests
- update CODEOWNERS file

2023-03-01 17:50 UTC, rodoviti requested changes

2023-03-01 17:50 UTC, rodoviti commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +public class PersonConnectorImpl implements PersonConnector {
```suggestion
class PersonConnectorImpl implements PersonConnector {
```

2023-03-01 17:50 UTC, rodoviti commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +    @PutMapping(value = "${rest-client.person.saveNamespacedId.path}", produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
```suggestion
```

2023-03-01 17:50 UTC, rodoviti commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +    @PatchMapping(value = "${rest-client.person.save.path}", produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
```suggestion
```

2023-03-01 17:50 UTC, rodoviti commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +    @GetMapping(value = "${rest-client.person.findById.path}", produces = MediaType.APPLICATION_JSON_VALUE)
```suggestion
```

2023-03-01 17:50 UTC, rodoviti commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +    @GetMapping(value = "${rest-client.person.findIdByNamespacedId.path}", produces = MediaType.APPLICATION_JSON_VALUE)
```suggestion
```

2023-03-01 17:50 UTC, rodoviti commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +        return findById(id, "");
```suggestion
        return findById(id, null);
```

2023-03-01 17:50 UTC, rodoviti commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +import org.springframework.web.bind.annotation.ResponseBody;
```suggestion
import org.springframework.stereotype.Service;
```

2023-03-01 17:50 UTC, rodoviti commented on core/src/main/java/it/pagopa/pdv/user_registry/core/UserServiceImpl.java
> +
```suggestion
```

2023-03-02 08:45 UTC, BenitoVisone commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +public class PersonConnectorImpl implements PersonConnector {
without "public" keyword I have problem during tests, view: https://github.com/pagopa/pdv-ms-user-registry/pull/15/commits/6abc21da5995db09c8d91cf7ca06fd215d48edc9

2023-03-02 08:46 UTC, BenitoVisone commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +    @PutMapping(value = "${rest-client.person.saveNamespacedId.path}", produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
fixed with https://github.com/pagopa/pdv-ms-user-registry/pull/15/commits/6abc21da5995db09c8d91cf7ca06fd215d48edc9

2023-03-02 08:46 UTC, BenitoVisone commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +    @PatchMapping(value = "${rest-client.person.save.path}", produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
fixed with https://github.com/pagopa/pdv-ms-user-registry/pull/15/commits/6abc21da5995db09c8d91cf7ca06fd215d48edc9

2023-03-02 08:46 UTC, BenitoVisone commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +    @GetMapping(value = "${rest-client.person.findById.path}", produces = MediaType.APPLICATION_JSON_VALUE)
fixed with https://github.com/pagopa/pdv-ms-user-registry/pull/15/commits/6abc21da5995db09c8d91cf7ca06fd215d48edc9

2023-03-02 08:46 UTC, BenitoVisone commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +        return findById(id, "");
fixed with https://github.com/pagopa/pdv-ms-user-registry/pull/15/commits/6abc21da5995db09c8d91cf7ca06fd215d48edc9

2023-03-02 08:46 UTC, BenitoVisone commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +import org.springframework.web.bind.annotation.ResponseBody;
fixed with https://github.com/pagopa/pdv-ms-user-registry/pull/15/commits/6abc21da5995db09c8d91cf7ca06fd215d48edc9

2023-03-02 08:47 UTC, BenitoVisone commented on core/src/main/java/it/pagopa/pdv/user_registry/core/UserServiceImpl.java
> +
fixed with https://github.com/pagopa/pdv-ms-user-registry/pull/15/commits/6abc21da5995db09c8d91cf7ca06fd215d48edc9

2023-03-02 08:47 UTC, BenitoVisone commented on connector/rest/src/main/java/it/pagopa/pdv/user_registry/connector/rest/PersonConnectorImpl.java
> +    @GetMapping(value = "${rest-client.person.findIdByNamespacedId.path}", produces = MediaType.APPLICATION_JSON_VALUE)
fixed with https://github.com/pagopa/pdv-ms-user-registry/pull/15/commits/6abc21da5995db09c8d91cf7ca06fd215d48edc9

2023-03-02 11:20 UTC, rodoviti approved these changes

2023-03-06 08:50 UTC, merged